version: "3.9"

services:
  netscan-tool:
    build: .
    container_name: netscan-tool
    hostname: netscan
    tty: true
    volumes:
      - ./docker_shared:/app/docker_shared
      - ./logs:/app/logs
      - ./server/files:/app/server/files

  netscan_elasticsearch_kibana:
    container_name: netscan-elasticsearch-kibana
    hostname: elasticsearch-kibana
    image: nshou/elasticsearch-kibana
    volumes:
      - ES_LOCAL_DATA:/usr/share/elasticsearch/data
      - ./config-elasticsearch.yml:/home/elasticsearch/elasticsearch-7.16.2/config/elasticsearch.yml
    ports:
      - 127.0.0.1:9200:9200
      - 127.0.0.1:5601:5601

  netscan_neo4j:
    container_name: netscan-neo4j
    hostname: neo4j
    image: neo4j:4.4.19-community
    volumes:
      - $HOME/neo4j/data:/data
    ports:
      - 127.0.0.1:7474:7474
      - 127.0.0.1:7687:7687

volumes:
  ES_LOCAL_DATA:
    driver: local
